pes-product-mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=demo
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbp4ss

pes-product-app:
  image: hub.magellancloud.com/pes/product:test
  links:
    - pes-product-mysql:mysql
  ports:
    - 8081:8081